import type { Article } from '../models/Article';
import { randomId } from '../utils/random';

export class ArticleFactory {
  static create(overrides: Partial<Article> = {}): Article {
    const id = randomId('article');

    return {
      title: `Playwright Portfolio Article ${id}`,
      description: 'A concise article generated by automated tests.',
      body: 'This article was created through the UI to validate the RealWorld publishing flow.',
      tagList: ['playwright', 'qa-automation'],
      ...overrides
    };
  }
}
